# Generated by Django 3.1.7 on 2021-03-15 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('elevation', models.FloatField()),
                ('crs', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adi', models.CharField(max_length=100)),
                ('rakim', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('surname', models.CharField(max_length=22)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=500)),
                ('rank', models.CharField(max_length=100)),
                ('workAt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adi', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('bagli_il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.il')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertName', models.CharField(max_length=22)),
                ('propertyType', models.CharField(max_length=15)),
                ('assetTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.assettype')),
            ],
        ),
        migrations.AddField(
            model_name='assettype',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.assettypesymbol'),
        ),
        migrations.CreateModel(
            name='AssetPropertyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=22)),
                ('assetID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.asset')),
                ('assetPropertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.assettypeproperties')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='assetTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.assettype'),
        ),
    ]
