# Generated by Django 2.2.12 on 2021-03-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='geom',
        ),
    ]
